# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
         patate:
            quality: 85
            filters:
                thumbnail: {size:[150,150], mode: outbound}
